baseURL = "https://blog.chengchih.me/"
languageCode = "zh-hant-tw"
title = "Cheng-Chih 的部落格"
theme = "github.com/CaiJimmy/hugo-theme-stack/v4"

defaultContentLanguage = "zh-tw"
hasCJKLanguage = true

[pagination]
  pagerSize = 10

[permalinks]
  post = "/:slug/"

[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = false

[[menu.main]]
identifier = "daily-life"
name = "日常生活"
url = "/categories/日常生活/"
weight = -70
[menu.main.params]
icon = "battery"

[[menu.main]]
identifier = "misc"
name = "雜談"
url = "/categories/雜談/"
weight = -60
[menu.main.params]
icon = "think"

[[menu.social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[menu.social.params]
icon = "rss"

[[menu.social]]
identifier = "email"
name = "Email"
url = "mailto:contact@chengchih.me"

[menu.social.params]
icon = "email"