baseURL = "https://blog.chengchih.me/"
languageCode = "zh-hant-tw"
title = "Cheng-Chih 的部落格"
theme = "github.com/CaiJimmy/hugo-theme-stack/v4"

defaultContentLanguage = "zh-tw"
hasCJKLanguage = true

[pagination]
  pagerSize = 10

[permalinks]
  post = "/:slug/"

[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = false

[[menu.main]]
identifier = "daily-life"
name = "日常生活"
url = "/categories/life/"
weight = -70
[menu.main.params]
icon = "battery"

[[menu.main]]
identifier = "misc"
name = "心情隨筆"
url = "/categories/thoughts/"
weight = -60
[menu.main.params]
icon = "think"

[[menu.social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[menu.social.params]
icon = "rss"

[[menu.social]]
identifier = "email"
name = "Email"
url = "mailto:contact@chengchih.me"

[menu.social.params]
icon = "email"

[related]
includeNewer = true
threshold = 50
toLower = true

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 70

[[related.indices]]
name = "series"
weight = 200

[[related.indices]]
name = "date"
weight = 10

[outputFormats.MainRSS]
mediaType = "application/rss+xml"
baseName = "main"
isPlainText = false
notAlternative = true

[outputs]
home = ["HTML", "RSS", "MainRSS"]