baseURL = "https://blog.chengchih.me/"
languageCode = "zh-hant-tw"
title = "我的部落格"
theme = "github.com/CaiJimmy/hugo-theme-stack/v4"

defaultContentLanguage = "zh-tw"
hasCJKLanguage = true

[pagination]
  pagerSize = 10

[permalinks]
  post = "/:slug/"

[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = false
