[goldmark.extensions.extras.superscript]
enable = true

[goldmark.extensions.extras.subscript]
enable = true

[goldmark.extensions.extras.mark]
enable = true

[goldmark.extensions.extras.insert]
enable = true

[goldmark.extensions.extras.delete]
enable = true

[goldmark.extensions]
strikethrough = false