mainSections = ["post"]

[sidebar]
emoji = "👋"

[article]
math = false
toc = true
readingTime = true

[comments]
enabled = false

[widgets]
homepage = [
    { type = "search" },
    { type = "archives", params = { limit = 5 } },
    { type = "categories", params = { limit = 10 } },
    { type = "tag-cloud", params = { limit = 10 } },
]

page = [
    { type = "toc" },
    { type = "archives", params = { limit = 5 } },
    { type = "categories", params = { limit = 10 } },
]

about = [
    { type = "toc" },
    { type = "archives", params = { limit = 3 } }
]